CREATE TABLE Personnel(Abbreviation VARCHAR PRIMARY KEY, "Name" VARCHAR NOT NULL UNIQUE);
CREATE TABLE Site(Code VARCHAR PRIMARY KEY, Site_name VARCHAR NOT NULL UNIQUE, "Location" VARCHAR NOT NULL, Latitude FLOAT NOT NULL, Longitude FLOAT NOT NULL, Area FLOAT NOT NULL, CHECK((Latitude BETWEEN -90 AND 90)), CHECK((Longitude BETWEEN -180 AND 180)), CHECK((Area > 0)), UNIQUE(Latitude, Longitude));
CREATE TABLE Species(Code VARCHAR PRIMARY KEY, Common_name VARCHAR NOT NULL UNIQUE, Scientific_name VARCHAR, Relevance VARCHAR);
CREATE TABLE Bird_nests(Book_page VARCHAR, "Year" INTEGER NOT NULL, Site VARCHAR NOT NULL, Nest_ID VARCHAR PRIMARY KEY, Species VARCHAR NOT NULL, Observer VARCHAR, Date_found DATE NOT NULL, how_found VARCHAR, Clutch_max INTEGER, floatAge FLOAT, ageMethod VARCHAR, CHECK(("Year" BETWEEN 1950 AND 2015)), CHECK((Date_found BETWEEN CAST(("Year" || '-01-01') AS DATE) AND CAST(("Year" || '-12-31') AS DATE))), CHECK((how_found IN ('searcher', 'rope', 'bander'))), CHECK((Clutch_max BETWEEN 0 AND 20)), CHECK((floatAge BETWEEN 0 AND 30)), CHECK((ageMethod IN ('float', 'lay', 'hatch'))), FOREIGN KEY (Site) REFERENCES Site(Code), FOREIGN KEY (Species) REFERENCES Species(Code), FOREIGN KEY (Observer) REFERENCES Personnel(Abbreviation));
CREATE TABLE Camp_assignment("Year" INTEGER NOT NULL, Site VARCHAR NOT NULL, Observer VARCHAR NOT NULL, "Start" DATE, "End" DATE, CHECK(("Year" BETWEEN 1950 AND 2015)), FOREIGN KEY (Site) REFERENCES Site(Code), FOREIGN KEY (Observer) REFERENCES Personnel(Abbreviation), CHECK(("Start" <= "End")), CHECK(("Start" BETWEEN CAST(("Year" || '-01-01') AS DATE) AND CAST(("Year" || '-12-31') AS DATE))), CHECK(("End" BETWEEN CAST(("Year" || '-01-01') AS DATE) AND CAST(("Year" || '-12-31') AS DATE))));
CREATE TABLE Snow_cover(Site VARCHAR, "Year" INTEGER NOT NULL, Date DATE, Plot VARCHAR, "Location" VARCHAR, Snow_cover FLOAT, Water_cover FLOAT, Land_cover FLOAT, Total_cover FLOAT, Observer VARCHAR, Notes VARCHAR, CHECK(("Year" BETWEEN 1990 AND 2018)), PRIMARY KEY(Site, Plot, "Location", Date), FOREIGN KEY (Site) REFERENCES Site(Code));
CREATE TABLE Bird_eggs(Book_page VARCHAR, "Year" INTEGER NOT NULL, Site VARCHAR NOT NULL, Nest_ID VARCHAR, Egg_num INTEGER, Length FLOAT NOT NULL, Width FLOAT NOT NULL, CHECK(("Year" BETWEEN 1950 AND 2015)), CHECK((Egg_num BETWEEN 1 AND 20)), CHECK(((Length > 0) AND (Length < 100))), CHECK(((Width > 0) AND (Width < 100))), PRIMARY KEY(Nest_ID, Egg_num), FOREIGN KEY (Site) REFERENCES Site(Code), FOREIGN KEY (Nest_ID) REFERENCES Bird_nests(Nest_ID));
CREATE VIEW Site_avg_snowcover AS SELECT Site, avg(Snow_cover) AS avg_snow_cover FROM Snow_cover GROUP BY Site ORDER BY avg_snow_cover DESC LIMIT 5;

